localization: # L10N strings for commands
  general: # All commands general messages, errors
    # None for now, wait until l10n update
settings: # Plugin settings
  general: # General plugin settings
    # Integration with other DoubleWhale plugins (such as CoinMaterial - https://github.com/whaleopop/CoinMaterial)
    # Values: "enabled"/"disabled"
    integrateDW: "enabled"
