# L10N strings for commands
localization:
  # All commands general messages, errors
  general:
    # None for now, wait until l10n update


# Plugin settings
settings:
  # Plugin settings
  general:
    # Integration with other DoubleWhale plugins (such as CoinMaterial - https://github.com/whaleopop/CoinMaterial)
    # Values: "enabled"/"disabled"
    integrateDW: "enabled"